#
# General settings
#

# Backup folder
BACKUP: /home/BACKUPS

# Last backups to keep
Keep last:
    Months: 120
    Weeks: 4
    Days: 7

# Compression command from stdin
Compression:
    Command: bzip2 -c >
    Extension: .bz2

#
# MySQL
#
MySQL:
    Command: mysqldump --compact --compress --host={host} --user={user} --password={password} {database} {ignore}
    Command ignore: --ignore-table={database}.{table}
    Databases:
        - database: Database name
          host: IP or host name
          user: Database user
          password: User password
          exclude: ['Table to exclude', ...]
        - ...

#
# PostgreSQL
#
PostgreSQL:
    Command: pg_dump --dbname=postgresql://{user}:{password}@{host}:5432/{database}
    Command ignore: --exclude-table={table}
    Databases:
        - database: Database name
          host: IP or host name
          user: Database user
          password: User password
          exclude: ['Table to exclude', ...]
        - ...
